import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import * as holtWinters from 'holtwinters'
import { useEffect, useState } from 'react'
const inter = Inter({ subsets: ['latin'] })
// var holtWinters = require('holtwinters')
console.log(holtWinters)
var getAugumentedDataset = holtWinters
//
var data = [1, 4, 5, 3, 1, 3, 4, 1, 2, 4, 5, 5]
var predictionLength = 4
//
var result = getAugumentedDataset(data, predictionLength)
console.log(result)  // DUDE, IT WORKS!


const ts = Array(10).fill(0).map((_, i) => i + Math.random() / 5)
const ARIMAPromise = require('arima/async')


// const ARIMAPromise = require('arima/async')


// const arima = require('arima')
// const [pred, errors] = arima(ts, 20, {
//   method: 0, // ARIMA method (Default: 0)
//   optimizer: 6, // Optimization method (Default: 6)
//   p: 1, // Number of Autoregressive coefficients
//   d: 0, // Number of times the series needs to be differenced
//   q: 1, // Number of Moving Average Coefficients
//   verbose: true // Output model analysis to console
// })
// console.log('pred', pred) // DUDE it works too!!


export default function Home() {
  const [pred, setPred] = useState([])
  useEffect(() => {
    ARIMAPromise.then(ARIMA => {
      const arima = new ARIMA({ p: 2, d: 1, q: 2, P: 0, D: 0, Q: 0, S: 0, verbose: false }).train(ts)
      const [pred, errors] = arima.predict(10)
      console.log('pred', pred)
      setPred(pred)
    })
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>{JSON.stringify(pred)}</p>
          <p>
            Get started by editing?&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
